### PR TITLE
Add past BarcelonaJS in Spain

### PR DESCRIPTION
**Pull request by tscharke**
Hopefully they add a new date in 2017 :-)

### CODE REVIEW

**Comment by prigara** [comment]
Thanks, @tscharke! Seems that it's a user group with regular meeting (at least that's what the [website says](http://barcelonajs.org/about/)) and not a conference. I'm not sure it makes sense to add meetups.

**Comment by tscharke** [comment]
@prigara Oh yes, you're right. No, it makes no sense to add meetups, this is a conference-list ;-)
Sorry for that.

**Comment by prigara** [comment]
@tscharke no problem. Have a great holiday season! 🎄

**Comment by tscharke** [comment]
@prigara thanks a lot :-) Merry christmas 🎄 and a happy new here 🎆 . Hope to see/hear you next year

**Pull request closed without merging**
